export const copy = {
  tagline: "easy to eat · 香港",
  title: "今日，食咩好？",
  subtitle: "由你而家嘅心情開始，慢慢揀到啱食嗰間。",
  decide: "幫我揀",
  history: "睇返之前",
  login: "用 Google 登入",
  logout: "登出",
  private: "你嘅私人搵食小幫手",
  setup: "登入服務尚未設定。設定完成後，就可以用獲邀帳戶登入。",
  foundation: "幾條問題，慢慢縮窄選擇",
  foundationDetail: "登入後可以儲存今次答案；餐廳搜尋仍未接通。",
  demoEntry: "試下點揀 · 示範",
  swipe: {
    categoryInstructions: "揀一類，或者都可以。可以用 Tab 移到選項，再撳 Enter。",
    either: "都可以",
    question: "跟住而家嘅心情揀",
    progress: "問題",
    approximately: "大約",
    instructions:
      "向左揀左邊，向右揀右邊，向上就都可以。亦可以撳下面按鈕，或用鍵盤 ← → ↑。",
    noWrongAnswer: "冇啱錯，啱你就得。",
    actions: "選擇答案",
    left: "向左揀",
    right: "向右揀",
    up: "向上揀",
    chosen: "你揀咗",
    saving: "儲存中…",
    unsaved: "未確認儲存",
    saved: "已儲存",
    tapHint: "唔想拖？撳一下都得。",
    failure: "未收到儲存確認。你嘅答案仲喺度，請重試。",
    retry: "重試儲存",
  },
  demo: {
    badge: "互動示範 · 非正式決策",
    notice:
      "三條固定示範問題，畀你試下操作。答案只留喺今次頁面，唔會加入歷史。",
    complete: "試完啦！",
    completeDetail:
      "以下係今次示範嘅答案。正式版本會按你嘅選擇，決定下一條問題。",
    home: "返主頁",
    testRetry: "試下重試流程",
    testRetryDetail:
      "模擬下一次答案已記錄，但未收到確認。重試會保留同一個答案，唔會重複記錄。",
    simulateFailure: "模擬下一次連線失敗",
    failureArmed: "已設定，下次會顯示重試",
    footer: "示範唔會提供餐廳推薦，亦唔會記錄已到訪。",
  },
  account: {
    label: "帳戶",
    loading: "準備中…",
    signingIn: "登入中…",
    allowed: "已登入，可以安心留低自己嘅選擇。",
    connectionFailed: "暫時未能連線，請登出後再試。",
    signInFailed: "未能完成登入，請再試一次。",
  },
};
